# spring.application.name=chatserver

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/chatdb?useSSL=false
      username: root
      password: 1234
  jpa:
    database: mysql
    # InnoDB ??
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # DB ?? ?? ??
    generate-ddl: true
    hibernate:
      ddl-auto: create # ?? ?? ?? ????
    show_sql: true

jwt:
  # chatServerSecretAccessTokenchatServerSecretAccessTokenchatServerSecretAccessToken
  secretKey: Y2hhdFNlcnZlclNlY3JldEFjY2Vzc1Rva2VuY2hhdFNlcnZlclNlY3JldEFjY2Vzc1Rva2VuY2hhdFNlcnZlclNlY3JldEFjY2Vzc1Rva2Vu
  expiration: 3000 # minute


