# spring.application.name=chatserver

spring:
  port: ${SERVER_PORT:8080}

  datasource:
      driver-class-name: ${DB_DRIVER}
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
    database: mysql
    # InnoDB ??
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # DB ?? ?? ??
    generate-ddl: true
    hibernate:
      ddl-auto: update # ?? ?? ?? ????
    show_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  # chatServerSecretAccessTokenchatServerSecretAccessTokenchatServerSecretAccessToken
  secretKey: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION} # minute

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


